import parseJSON from "./parseJSON";
export const json = new parseJSON();

export const path = {};

export const img_path = {
  warpResult: "../assets/warp-results/",
};

const baseWeapons = [
  "amber",
  "arrows",
  "chorus",
  "collapsing-sky",
  "cornucopia",
  "darting-arrow",
  "data-bank",
  "fine-fruit",
  "loop",
  "meshing-cogs",
  "multiplication",
  "passkey",
  "shattered-home",
  "void",
  "sagacity",
  "hidden-shadow",
  "adversarial",
  "mediation",
  "defense",
  "pioneering",
  "mutual-demise",
];

const allChars = [
  "arlan",
  "asta",
  "dan-heng",
  "herta",
  "hook",
  "march-7th",
  "natasha",
  "pela",
  "qingque",
  "sampo",
  "serval",
  "sushang",
  "tingyun",
  "bailu",
  "blade",
  "bronya",
  "clara",
  "gepard",
  "himeko",
  "jing-yuan",
  "kafa",
  "luocha",
  "seele",
  "silver-fox",
  "welt",
  "yanqing",
];

const allWeapons = [
  "a-secret-vow",
  "carve-the-moon-weave-the-clouds",
  "dance-dance-dance",
  "day-one-of-my-new-life",
  "eyes-of-the-prey",
  "fermata",
  "geniuses-repose",
  "good-night-and-sleep-well",
  "landaus-choice",
  "make-the-world-clamor",
  "memories-of-the-past",
  "nowhere-to-run",
  "only-silence-remains",
  "past-and-future",
  "perfect-timing",
  "planetary-rendezvous",
  "post-op-conversation",
  "quid-pro-quo",
  "resolution-shines-as-pearls-of-sweat",
  "return-to-darkness",
  "river-flows-in-spring",
  "shared-feeling",
  "subscribe-for-more",
  "swordplay",
  "the-birth-of-the-self",
  "the-moles-welcome-you",
  "the-seriousness-of-breakfast",
  "this-is-me",
  "today-is-another-peaceful-day",
  "trend-of-the-universal-market",
  "under-the-blue-sky",
  "warmth-shortens-cold-nights",
  "we-are-wildfire",
  "we-will-meet-again",
  "woof-walk-time",
  "before-dawn",
  "but-the-battle-isnt-over",
  "cruising-in-the-stellar-sea",
  "echoes-of-the-coffin",
  "incessant-rain",
  "in-the-name-of-the-world",
  "in-the-night",
  "moment-of-victory",
  "night-on-the-milky-way",
  "on-the-fall-of-an-aeon",
  "patience-is-all-you-need",
  "sleep-like-the-dead",
  "something-irreplaceable",
  "texture-of-memories",
  "the-unreachable-side",
  "time-waits-for-no-one",
];

const allBannersAbbr = [
  "childe_alt",
  "childe_alt_ei",
  "hutao",
  "hutao_ei",
  "xiao",
  "xiao_ei",
  "ganyu",
  "ganyu_ei",
  "albedo",
  "albedo_ei",
  "zhongli",
  "zhongli_ei",
  "childe",
  "childe_ei",
  "klee",
  "klee_ei",
  "venti",
  "venti_ei",
  "standard",
];

export { allChars, allWeapons, allBannersAbbr, baseWeapons };
